export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_REQUEST = "CREATE_REQUEST";
export const CREATE_FAILURE = "CREATE_FAILURE";

export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";

export const UPLOAD_PHOTO = "UPLOAD_PHOTO";

export const CREATE_PROFILE = "CREATE_PROFILE";